title: Aplikacje.gov.pl
description: Aplikacje.gov.pl
baseurl: ""

collections:
  - applications
  - declarations
  - abouts
  - benefits
  - local-declarations
  - other-declarations
  - parlament-declarations

gems: [ kramdown ]

markdown: kramdown
