# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aplikacje.gov.pl
description: Aplikacje.gov.pl
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 5
collections:
  - applications
  - declarations
  - abouts
  - benefits
  - local-declarations
  - other-declarations
  - parlament-declarations

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
